# Generated by Django 3.2.4 on 2021-06-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=100, verbose_name='岗位名称')),
                ('company_name', models.CharField(max_length=100, verbose_name='公司名称')),
                ('company_class', models.CharField(max_length=100, verbose_name='公司性质')),
                ('company_scale', models.CharField(max_length=100, verbose_name='公司规模')),
                ('detail_url', models.URLField(verbose_name='详情链接')),
                ('position_base', models.CharField(max_length=100, verbose_name='城市')),
                ('position_experience', models.CharField(max_length=100, verbose_name='工作经验')),
                ('position_degree', models.CharField(max_length=100, verbose_name='最低学历')),
                ('position_vacancies', models.IntegerField(verbose_name='招聘人数')),
                ('position_min_salary', models.CharField(max_length=50, verbose_name='最低薪资')),
                ('position_max_salary', models.CharField(max_length=50, verbose_name='最高薪资')),
                ('position_update_time', models.CharField(max_length=100, verbose_name='更新时间')),
                ('position_description', models.TextField(verbose_name='岗位描述')),
                ('position_welfare', models.CharField(max_length=100, verbose_name='职位福利')),
                ('position_location', models.CharField(max_length=100, verbose_name='工作地点')),
            ],
        ),
    ]
